server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://eketxubjycctpw:1888aa10ae93c53824708d2e833c55e39283a346defdd0cf36002beacebe5c43@ec2-34-230-115-172.compute-1.amazonaws.com:5432/d5mv2762pjq2mv
    username: eketxubjycctpw
    password: 1888aa10ae93c53824708d2e833c55e39283a346defdd0cf36002beacebe5c43
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander